name: firebase deploy

on:
  repository_dispatch:
    types: [update_post]
  push:
    branches:
      - master

env:
  cache-version: v7

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-node-

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: test
        env:
          TZ: 'Asia/Tokyo'
        run: yarn test:cov

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: 'coverage/lcov.info'

      # Storybookをgithub pagesにホスティング
      - name: build Storybook
        run: yarn build-storybook

      - name: deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static

      # Nuxtをfirebase hostingにホスティング
      - name: create .env file
        run: echo "${{ secrets.ENV_FIREBASE }}" > .env

      - name: build Nuxt
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          MICRO_CMS: ${{ secrets.MICRO_CMS }}
          ARTICLE_URL: ${{ secrets.ARTICLE_URL }}
          TAG_URL: ${{ secrets.TAG_URL }}
          CATEGORY_URL: ${{ secrets.CATEGORY_URL }}
        run: yarn generate

      - name: deploy to Firebase Hosting
        run: yarn firebase deploy --only hosting:production --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
