name: update article

# payloadを生成するだけなので、テストやlintを行わない

on:
  repository_dispatch:
    types: [update_post]
      
env:
  cache-version: v1

jobs:
   build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-node-

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

      - name: build
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MICRO_CMS: ${{ secrets.MICRO_CMS }}
        ARTICLE_URL: ${{ secrets.ARTICLE_URL }}
        TAG_URL: ${{ secrets.TAG_URL }}
        CATEGORY_URL: ${{ secrets.CATEGORY_URL }}
      run: yarn generate:static

    - name: deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}